export const DRAWING_LIST_REQUEST = "DRAWING_LIST_REQUEST";
export const DRAWING_LIST_SUCCESS = "DRAWING_LIST_SUCCESS";
export const DRAWING_LIST_FAILURE = "DRAWING_LIST_FAILURE";

export const DRAWING_SAVE_REQUEST = "DRAWING_SAVE_REQUEST";
export const DRAWING_SAVE_SUCCESS = "DRAWING_SAVE_SUCCESS";
export const DRAWING_SAVE_FAILURE = "DRAWING_SAVE_FAILURE";

export const DRAWING_DELETE_REQUEST = "DRAWING_DELETE_REQUEST";
export const DRAWING_DELETE_SUCCESS = "DRAWING_DELETE_SUCCESS";
export const DRAWING_DELETE_FAILURE = "DRAWING_DELETE_FAILURE";
